name: lerna publish

on:
  push:
    branches:
      - release
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: Update npm_token
        run: sed -e "s/NPM_TOKEN/${NPM_TOKEN}/" .npmrc
      - name: Configure Git User
        run: |
          git config --global user.email "bessel@besselstudio.com"
          git config --global user.name "@$GITHUB_ACTOR"
      - name: Install dependencies
        run: yarn install
      - run: yarn lerna publish --conventional-commits --yes
